// Standalone native Wear OS project — intentionally SEPARATE from the Expo-managed `android/`
// (which is regenerated by `expo prebuild`). Open this `wear/` folder directly in Android Studio.
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AgentrixWear"
include(":app")
